### ISSUE TITLE
[Feature Request] Add support for different objectives, criterias and entry types

### ISSUE THREAD

**Issue by inxomnyaa** [Ifera/ScoreFactory#1]
I'd like to use this virion, but for what i want to do (actual scoreboards, that do not use lines but scores) i would need support for different objectives, criterias (not just dummy) and entry types (not just fakeplayer).

Also support for the belowname slot would be great (player->setscore), which is single line

**Comment by Ifera** [comment]
Hopefully this was what you required.

**Comment by inxomnyaa** [comment]
Looks fine. I have to test :P Thanks
